spring.application.name=config-server
server.port=8888
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=file:///home/pentagon/projects/distribuirani_sistemi/library-system/config-repo
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=config-server
